server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_practice?charset=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create